//+------------------------------------------------------------------+
//|                                           QuantumFileClient.mq4 |
//|                        Generated by Gemini Quantum Agent          |
//|                        FIXED VERSION                              |
//+------------------------------------------------------------------+
#property copyright "Gemini Quantum Agent"
#property link      "https://google.com"
#property version   "1.01"
#property strict

// Input Parameters
input int LookbackCandles = 50;
input double LotSize = 0.1;

// FIX #3: Changed default from 2000 to 500
// 500 points = 50 pips on 5-digit broker (which is the industry standard)
// README said "StopLoss 500 = 50 pips" but code had 2000 = 200 pips!
input int StopLossPoints = 500;   // 50 pips for 5-digit broker
input int TakeProfitPoints = 0;

// Internal State
int lastBarTime = 0;
string reqFileName = "quantum_request.txt";
string respFileName = "quantum_response.txt";

//+------------------------------------------------------------------+
//| Expert Initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   Print("QuantumFileClient: Initialized (FIXED). Using File I/O Bridge.");
   Print("Data Path: " + TerminalInfoString(TERMINAL_DATA_PATH) + "\\MQL4\\Files");
   Print("StopLoss: " + IntegerToString(StopLossPoints) + " points (" + 
         DoubleToString(StopLossPoints / 10.0, 1) + " pips on 5-digit)");
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert Tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Check for New Bar
   if(Time[0] == lastBarTime) return;
   
   lastBarTime = (int)Time[0];
   
   Print("QuantumFileClient: New Bar. Writing request to file...");
   
   // 1. Prepare JSON
   string json = "{\"closes\": [";
   for(int i = LookbackCandles; i >= 1; i--)
     {
      json += DoubleToString(Close[i], 5);
      if(i > 1) json += ", ";
     }
   json += "]}";
   
   // 2. Write to File
   int file_handle = FileOpen(reqFileName, FILE_WRITE|FILE_TXT|FILE_ANSI);
   if(file_handle != INVALID_HANDLE)
     {
      FileWrite(file_handle, json);
      FileClose(file_handle);
     }
   else
     {
      Print("Error: Could not write to " + reqFileName + ". Error=" + IntegerToString(GetLastError()));
      return;
     }

   // 3. Wait for Response (Simple Polling with Timeout)
   int attempts = 0;
   string response = "";
   bool received = false;
   
   while(attempts < 20) // 20 * 500ms = 10 seconds timeout
     {
      Sleep(500);
      
      // Check if response file exists
      if(FileIsExist(respFileName))
        {
         int read_handle = FileOpen(respFileName, FILE_READ|FILE_TXT|FILE_ANSI);
         if(read_handle != INVALID_HANDLE)
           {
             string line = FileReadString(read_handle);
             if(StringLen(line) > 5) 
               {
                response = line;
                received = true;
                FileClose(read_handle);
                
                // Delete response so we don't read it again next time
                FileDelete(respFileName);
                break;
               }
             FileClose(read_handle);
           }
        }
      attempts++;
     }
     
   if(received)
     {
      Print("QuantumFileClient: Received Signal: " + response);
      ProcessSignal(response);
     }
   else
     {
      Print("QuantumFileClient: Timed out waiting for Python bridge.");
     }
  }

//+------------------------------------------------------------------+
//| Logic                                                            |
//+------------------------------------------------------------------+
void ProcessSignal(string json)
  {
   int signal = ParseJsonInt(json, "signal");
   double conf = ParseJsonDouble(json, "confidence");
   
   Print("Signal=" + IntegerToString(signal) + " Conf=" + DoubleToString(conf, 4));
   
   // DYNAMIC LOT SIZING LOGIC
   // FIX: Now that confidence is correctly calculated (0.5 to 1.0 range),
   // the lot sizing will work as intended.
   // 
   // With the OLD buggy code, confidence was always >= 0.5, so:
   //   dynamicLots = 0.5 / 10 = 0.05 minimum (too high!)
   //
   // With FIXED code, if model is uncertain (conf ~0.55), lots will be small.
   // Formula: conf / 10.0 → 0.55 conf = 0.055 lots
   
   double dynamicLots = conf / 10.0; 
   
   // Clamp to safe range
   if(dynamicLots > 0.09) dynamicLots = 0.09;  // Max 0.09
   if(dynamicLots < 0.01) dynamicLots = 0.01;  // Min 0.01
   
   dynamicLots = NormalizeDouble(dynamicLots, 2);
   
   Print("Dynamic Lots: " + DoubleToString(dynamicLots, 2) + " (Confidence: " + DoubleToString(conf, 4) + ")");

   double sl = 0, tp = 0;
   
   if(signal == 1)
     {
      CloseAllRequests(OP_SELL);
      if(CountOrders(OP_BUY) == 0)
        {
         if(StopLossPoints > 0) sl = Ask - StopLossPoints * Point;
         if(TakeProfitPoints > 0) tp = Ask + TakeProfitPoints * Point;
         int ticket = OrderSend(Symbol(), OP_BUY, dynamicLots, Ask, 3, sl, tp, "Quantum Long", 0, 0, Blue);
         if(ticket < 0) Print("OrderSend BUY failed: " + IntegerToString(GetLastError()));
        }
     }
   else if(signal == -1)
     {
      CloseAllRequests(OP_BUY);
      if(CountOrders(OP_SELL) == 0)
        {
         if(StopLossPoints > 0) sl = Bid + StopLossPoints * Point;
         if(TakeProfitPoints > 0) tp = Bid - TakeProfitPoints * Point; 
         int ticket = OrderSend(Symbol(), OP_SELL, dynamicLots, Bid, 3, sl, tp, "Quantum Short", 0, 0, Red);
         if(ticket < 0) Print("OrderSend SELL failed: " + IntegerToString(GetLastError()));
        }
     }
   // signal == 0: No action (model uncertain)
  }

// JSON Parsing Helpers
int ParseJsonInt(string json, string key)
  {
   int start = StringFind(json, "\"" + key + "\":");
   if(start == -1) return 0;
   start = start + StringLen(key) + 3; 
   int end = StringFind(json, ",", start);
   if(end == -1) end = StringFind(json, "}", start);
   string val = StringSubstr(json, start, end - start);
   return (int)StringToInteger(val);
  }

double ParseJsonDouble(string json, string key)
  {
   int start = StringFind(json, "\"" + key + "\":");
   if(start == -1) return 0.0;
   start = start + StringLen(key) + 3;
   int end = StringFind(json, ",", start);
   if(end == -1) end = StringFind(json, "}", start);
   string val = StringSubstr(json, start, end - start);
   return StringToDouble(val);
  }

void CloseAllRequests(int type)
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderSymbol() == Symbol() && OrderType() == type)
           {
            bool res = false;
            if(type == OP_BUY) res = OrderClose(OrderTicket(), OrderLots(), Bid, 3, CLR_NONE);
            else if(type == OP_SELL) res = OrderClose(OrderTicket(), OrderLots(), Ask, 3, CLR_NONE);
           }
        }
     }
  }

int CountOrders(int type)
  {
   int count = 0;
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderSymbol() == Symbol() && OrderType() == type) count++;
        }
     }
   return count;
  }
